export {default as Home} from './Home'
export {default as Movies} from './Movies'
export {default as TvShows} from './TvShows'
export {default as TopRatedPage} from './TopRatedPage'
export {default as TrendingPageMovies} from './TrendingPageMovies'
export {default as TrendingPageTv} from './TrendingPageTv'
export {default as SinglePage} from './SinglePage'